model_name: fastino/gliner2-base-v1
batch_size: 4
include_confidence: true
default_threshold: 0.5

entities:
  - person
  - organization: "Company or institution names"
  - product

classifications:
  - sentiment:
      labels:
        positive: "Favorable tone"
        neutral: "Informational or balanced tone"
        negative: "Critical or concerned tone"
      threshold: 0.55
  - name: document_type
    labels:
      - label: news
        description: "Informative article"
      - label: review
      - label: opinion

structures:
  - announcement:
      - name: subject
        dtype: str
        description: Main announcement topic
      - name: date
        dtype: str
        description: Key dates mentioned
      - name: product
        dtype: str
        description: Linked products
      - name: highlights
        dtype: list
        description: Important bullet points
